### ISSUE TITLE
Indexing problem

### ISSUE THREAD

**Issue by stepanLav** [novasamatech/subquery-proxy#13]
```
2024-07-21T01:37:37.546Z <WorkerService-#2> ERROR Failed to index block 4461467: Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33
    at Vr (webpack://subquery-proxy/node_modules/@polkadot/util-crypto/address/encode.js:13:14)
    at e.checkAndGetAccount (webpack://subquery-proxy/src/utils/checkAndGetAccount.ts:12:54)
    at async Promise.all (index 0)
    at async e.handleMultisigCall (webpack://subquery-proxy/src/mappings/handlers/multisigCallHandler.ts:13:10) Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33
```
<img width="1047" alt="Screenshot 2024-07-21 at 04 38 40" src="https://github.com/user-attachments/assets/bf4631f9-e8f5-4e91-9425-eb44e2aa4ace">

**Comment by stepanLav** [comment]
fixed
